os: linux
dist: bionic
language: python
cache: pip
before_install:
  - sudo apt install software-properties-common
  #install firejail
  - sudo add-apt-repository -y ppa:deki/firejail
  - sudo apt-get update
  - sudo apt-get install firejail
  #install GCC
  - sudo apt-get install gcc

script:
  - pytest
  - pydoctor --make-html --html-output=docs --add-package=src --project-name=EXecutioner

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: docs
  on:
    branch: master