workspace: "playground"
languages:
  python3:
    fileFormat: "{filename}.py"
    compileCommand: "python3 -m py_compile {source}"
    executeCommand: "python3 '{compiled_file}'"
    compiledFormat: "{source}"
    timeLimit: "10"
    memLimit: "100"
  C:
    fileFormat: "{filename}.c"
    compileCommand: "gcc {source} -o {source}.out"
    executeCommand: "./{compiled_file}"
    compiledFormat: "{source}.out"
    timeLimit: "5"
    memLimit: "100"
