name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: cache setup
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - run: sudo apt install software-properties-common
      #install firejail
      - run: sudo add-apt-repository -y ppa:deki/firejail
      - run: sudo apt-get update
      - run: sudo apt-get install firejail

      - name: Install GCC
        run: sudo apt-get install gcc

      - name: Generate Report
        run: |
          pytest --cov=executioner -n 4
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        # with:
